AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-deploy

  Sample SAM Template for test-deploy
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  GetData:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: Scan.getData
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getData
            Method: get
      Policies:
          DynamoDBCrudPolicy:
             TableName: !Ref UserTable
  Adddata:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: Add.Adddata
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addData
            Method: post
      Policies:
          DynamoDBCrudPolicy:
             TableName: !Ref UserTable
  Deletedata:
     Type: AWS::Serverless::Function
     Properties:
        CodeUri: src/functions/
        Handler: Delete.Deletedata
        Runtime: nodejs14.x
        Architectures:
           - x86_64
        Events:
          HelloWorld:
             Type: Api
             Properties:
               Path: /delete/{id}
               Method: delete
        Policies:
           DynamoDBCrudPolicy:
              TableName: !Ref UserTable

  
        
  
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: data
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
       - AttributeName: id
         KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DynamoDBdApi:
    Description: "API Gateway endpoint URL for Dynamodb operation like scan put and delete"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
